server:
  port: 8081

spring:
  application:
    name: filierafacile
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/filierafacile?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD} # Set this environment variable!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # ATTENZIONE: Solo per sviluppo! Usa 'update' in produzione
    show-sql: true # Mostra le query SQL nel log (utile per debug)
    format-sql: true # Formatta le query SQL per leggibilità
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: false # Disabilitato per ora, useremo Hibernate per creare il schema

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # Log dei parametri delle query

# Environment variables needed:
# DB_URL (optional, defaults to localhost MySQL)
# DB_USERNAME (optional, defaults to root)
# DB_PASSWORD (required, no default)